### ISSUE TITLE
Can you provide training script?

### ISSUE THREAD

**Issue by iamjoseph331** [clovaai/EResFD#1]
Hi, 
I am interested in this work and want to dive in deeper.
Can you provide training code for the results?

Also, how is eresfd_16 different from eresfd?

Thank you for the work.

**Comment by doublejtoh** [comment]
@iamjoseph331
Unfortunately, we are not providing training scripts due to internal circumstances currently.
Since we used training scripts from https://github.com/yxlijun/S3FD.pytorch, you might reproduce results with it.
See Appendix A.2 for detailed training schemes (lr, etc).

[eresfd_16.py](https://github.com/clovaai/EResFD/blob/main/models/eresfd_16.py) corresponds to Figure 2 (EResFD-1x) in the manuscript.

Appreciate for your interest!

**Comment by RoyiAvital** [comment]
In the demo section you write: `python3 demo.py --model ./weights/eresfd_16.pth` yet in the `weights` folder there are 5 different models:

![image](https://user-images.githubusercontent.com/7347975/188519990-d79a32da-71f7-46d5-af8e-7f8f9a22cc7e.png)

Could you share the difference between them?
